---
title: "Homework 2"
author: "Jyoti Ankam"
date: "September 28, 2018"
output: github_document
---

```{r}

library(tidyverse)

```

Problem 1:
```{r}

nyc_transit = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line:entry, vending, ada) %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))

```


```{r}

ada_compliant = distinct(nyc_transit, line, station_name, ada)

sum(ada_compliant$ada)

nrow(ada_compliant)
```


```{r}

ent_vend_df = mutate(nyc_transit, vending = recode(vending, "YES" = TRUE, "NO" = FALSE),
                  entry_vend = !(entry == vending))

prop_vending = sum(ent_vend_df$entry_vend)/nrow(ent_vend_df)
  
```


```{r}

reformat_df = gather(ent_vend_df, key = route_num, value = train, route1:route11) %>% 
  separate(route_num, into = c("delete", "route"), sep = 5) %>% 
  select(everything(), -delete) %>% 
  distinct(line, station_name, train, ada) %>% 
  filter(train == "A")

```

There are `r nrow(reformat_df)` distinct stations that serve the A train. From the distinct stations that serve the A train, `r sum(reformat_df$ada)` are ADA compliant.

Problem 2:

```{r}

trash_wheel_df = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "Mr. Trash Wheel", cellranger::cell_cols(1:13)) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster), dumpster != 23220) %>% 
  mutate(sports_balls = as.integer(round(sports_balls, 0)))

```

Reading and cleaning precipitation data 2016 and 2017:

```{r}

precip_2016 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2016 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = 2016) 


precip_2017 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2017 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = 2017) %>% 
  filter(!is.na(total))

```


Combining the datasets for 2016 and 2017:

```{r}

precip_16_17_df = bind_rows(precip_2016, precip_2017)
  month.name[precip_16_17_df$month]

month_df = pull(precip_16_17_df, month) %>% 
  tibble(month_name = month.name[month_df])


```

Problem 3: Installing the package

```{r}

# install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")

library(p8105.datasets)

data(brfss_smart2010)

```

